language: cpp
os:
    - linux
dist: xenial
compiler:
  - gcc
sudo: required

addons:
    apt:
        update: true
        packages:
            - flex
            - bison
            - cmake
            - cmake-data
            - python3.5
            - python3.5-dev
            - python3.5-dbg
            - libxml2-utils
            - libsqlite3-dev
            - python3-pip

script:
    - sudo pip3 install pytest
    - mkdir build
    - cd build
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dbuild_tests=ON -DPYTHON_INCLUDE_DIR=/usr/include/python3.5dm -DPYTHON_LIBRARY=/usr/lib/python3.5/config-3.5dm-x86_64-linux-gnu/libpython3.5dm.so ..
    - cmake --build . --target all
    - ctest -V
