language: cpp
os:
    - linux-ppc64le 
    - linux
dist: xenial
compiler:
  - gcc
  - clang
sudo: required

addons:
    apt:
        update: true
        packages:
            - texlive
            - texlive-generic-recommended
            - texlive-extra-utils
            - texlive-latex-extra
            - texlive-font-utils
            - ghostscript
            - libxml2-utils
            - cmake
            - cmake-data

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
