language: cpp
dist: xenial
sudo: required
compiler:
  - gcc
os:
  - linux

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
    before_cache:
      - rm -f $HOME/.cache/pip/log/debug.log

branches:
  except:
    - master

addons:
    apt:
        packages:
            - flex
            - bison
            - cmake
            - cmake-data
            - python3.5
            - python3.5-dev
            - python3.5-dbg
            - python3-pip
            - libxml2-utils
            - libsqlite3-dev

script:
    - pip3 install --user pytest docutils
    - mkdir build
    - cd build
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dbuild_tests=ON -DPYTHON_INCLUDE_DIR=/usr/include/python3.5dm -DPYTHON_LIBRARY=/usr/lib/python3.5/config-3.5dm-x86_64-linux-gnu/libpython3.5dm.so ..
    - cmake --build . --target all
    - ctest -V
